# Generated by Django 5.0.6 on 2024-06-04 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community_app', '0001_initial'),
        ('people_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('id_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.community')),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_app.people')),
            ],
        ),
    ]
