# Generated by Django 4.2.13 on 2024-06-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_remove_project_end_date_remove_project_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id_community',
            new_name='fk_community',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='id_people',
            new_name='fk_people',
        ),
    ]
