# Generated by Django 5.0.6 on 2024-05-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.TimeField()),
                ('adress', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('pix_key', models.CharField(max_length=500)),
                ('pix_key_owner', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('pdf_link', models.CharField(max_length=300)),
                ('questionary_link', models.CharField(max_length=200)),
                ('category', models.CharField(choices='', max_length=20)),
            ],
        ),
    ]
