# Generated by Django 5.0.6 on 2024-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='pdf_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='pix_key',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='questionary_link',
            field=models.URLField(max_length=100),
        ),
    ]
