# Generated by Django 5.0.6 on 2024-05-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_event_link_alter_event_pdf_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(choices='', default=50, max_length=100),
            preserve_default=False,
        ),
    ]
