# Generated by Django 5.0.6 on 2024-05-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_event_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[(1, 'Feira'), (2, 'Festividade'), (3, 'Celebração')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[(1, 'Presencial'), (2, 'Virtual'), (3, 'Híbrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='profile_image',
            field=models.ImageField(height_field=30, upload_to='', width_field=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
