# Generated by Django 4.2.13 on 2024-06-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_alter_event_category_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('F', 'Feira'), ('Ft', 'Festividade'), ('Cl', 'Celebração')], default='Vazio', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('H', 'Híbrido')], default='Vazio', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pdf_link',
            field=models.URLField(max_length=100, null=True, verbose_name='Link para PDF'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pix_key',
            field=models.URLField(max_length=100, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='event',
            name='profile_image',
            field=models.ImageField(upload_to='media/events/', verbose_name='Imagem de perfil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='questionary_link',
            field=models.URLField(max_length=100, null=True, verbose_name='Link para questionário'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
