# Generated by Django 5.0.6 on 2024-05-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_rename_description_event_body_event_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='body',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
