# Generated by Django 5.0.6 on 2024-06-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_remove_event_profile_image'),
        ('events_app', '0005_alter_event_body_alter_event_category_and_more'),
    ]

    operations = [
    ]
