# Generated by Django 5.0.6 on 2024-06-12 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_merge_20240610_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fk_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events_app.event'),
        ),
    ]
