# Generated by Django 5.0.6 on 2024-05-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0006_remove_event_body_remove_event_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='body',
        ),
    ]
