# Generated by Django 5.0.6 on 2024-05-22 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_rename_description_event_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[(1, 'Ruim'), (2, 'Bom'), (3, 'Muito bom')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
