# Generated by Django 5.0.6 on 2024-05-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_review_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
