# Generated by Django 4.2.13 on 2024-06-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0008_alter_event_body_alter_event_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
