# Generated by Django 5.0.6 on 2024-05-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0009_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('F', 'Feira'), ('Ft', 'Festividade'), ('Cl', 'Celebração')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('H', 'Híbrido')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.CharField(choices=[('R', 'Ruim'), ('B', 'Bom'), ('Mb', 'Muito bom')], max_length=20),
        ),
    ]
