# Generated by Django 5.0.6 on 2024-05-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0010_alter_event_category_alter_event_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
