# Generated by Django 5.0.6 on 2024-05-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0011_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='profile_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
