# Generated by Django 5.0.6 on 2024-05-17 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('COMMUNITY', 'Comunidade'), ('Tourist attraction', 'Ponto Turístico')], max_length=50)),
                ('foundation_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('news_text', models.TextField()),
                ('publish_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('id_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.community')),
            ],
        ),
    ]
