# Generated by Django 5.0.6 on 2024-06-06 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('category', models.CharField(choices=[('COMMUNITY', 'Comunidade'), ('Tourist attraction', 'Ponto Turístico')], max_length=50, verbose_name='Categoria')),
                ('foundation_date', models.DateField(verbose_name='Data de Fundação')),
                ('begin_visit_time', models.TimeField(verbose_name='Hora de Início da Visita')),
                ('end_visit_time', models.TimeField(verbose_name='Hora de Fim da Visita')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('link', models.URLField(verbose_name='Link')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Logotipo')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('news_text', models.TextField()),
                ('publish_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('id_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.community')),
            ],
        ),
    ]
