# Generated by Django 5.0.6 on 2024-06-06 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='new',
            name='id_community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.community', verbose_name='Comunidade'),
        ),
        migrations.AlterField(
            model_name='new',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='new',
            name='news_text',
            field=models.TextField(verbose_name='Texto da Notícia'),
        ),
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateField(verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
