# Generated by Django 5.0.6 on 2024-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='community',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
