# Generated by Django 5.0.6 on 2024-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_alter_community_id_alter_community_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
