# Generated by Django 5.0.6 on 2024-05-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_alter_community_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
