# Generated by Django 4.2.13 on 2024-06-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community_app', '0002_alter_new_category_alter_new_id_community_and_more'),
        ('events_app', '0001_initial'),
        ('project_app', '0002_remove_project_end_date_remove_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('category', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('fk_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.community')),
                ('fk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.event')),
                ('fk_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community_app.new')),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.project')),
            ],
        ),
    ]
