# Generated by Django 5.0.6 on 2024-06-04 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorie',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PEOPLE', 'Pessoa'), ('INTERPRISE', 'Empresa')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='example@example.com', max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PEOPLE', 'Pessoa'), ('INTERPRISE', 'Empresa')], max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('link', models.URLField(null=True)),
                ('fk_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_app.subcategorie')),
            ],
        ),
    ]
