# Generated by Django 5.0.6 on 2024-05-18 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='fk_login',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='fk_category',
            new_name='fk_subcategory',
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
