# Generated by Django 5.0.6 on 2024-06-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subcategorie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
