# Generated by Django 5.0.6 on 2024-05-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0002_remove_people_fk_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Subcategorie',
        ),
    ]
