# Generated by Django 5.0.6 on 2024-05-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0003_rename_subcategory_subcategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorie',
            name='category',
            field=models.CharField(choices=[('PEOPLE', 'Pessoa'), ('INTERPRISE', 'Empresa')], max_length=100),
        ),
    ]
