# Generated by Django 5.0.6 on 2024-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0004_alter_subcategorie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
