# Generated by Django 5.0.6 on 2024-05-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0006_alter_people_email_alter_people_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorie',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
