# Generated by Django 5.0.6 on 2024-05-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0007_alter_subcategorie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
